# .github/workflows/terraform-apply-prod.yml

name: Terraform Apply Production

on:
  push:
    branches:
      - main

jobs:
  terraform-apply-prod:
    runs-on: ubuntu-latest

    permissions:
      id-token: write
      contents: read

    environment:
      name: production

    steps:
      - name: Checkout Repository
        uses: actions/checkout@v4

      - name: Configure AWS Credentials
        uses: aws-actions/configure-aws-credentials@v4
        with:
          role-to-assume: ${{ secrets.AWS_PROD_ROLE_ARN }}
          aws-region: me-south-1

      - name: Setup Terraform
        uses: hashicorp/setup-terraform@v3

      - name: Terraform Init
        run: terraform init

      - name: Terraform Plan
        run: terraform plan -out=tfplan

      - name: Terraform Apply
        run: terraform apply -auto-approve tfplan