# .github/workflows/terraform-apply-dev.yml

name: Terraform Apply Dev

on:
  push:
    branches:
      - develop

jobs:
  terraform-apply-dev:
    runs-on: ubuntu-latest

    permissions:
      id-token: write
      contents: read

    environment:
      name: dev

    steps:
      - name: Checkout Repository
        uses: actions/checkout@v4

      - name: Configure AWS Credentials
        uses: aws-actions/configure-aws-credentials@v4
        with:
          role-to-assume: ${{ secrets.AWS_DEV_ROLE_ARN }}
          aws-region: ap-south-1

      - name: Setup Terraform
        uses: hashicorp/setup-terraform@v3

      - name: Terraform Init
        run: terraform init

      - name: Terraform Apply
        run: terraform apply -auto-approve